version: "3"
services:
  # dashboard:
  #   build: ./dashboard
  #   ports:
  #     - "3000:3000"
  db:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123
  api:
    build: ./api
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  dbdata:
